version: "2.4"
services:
  app-web:   
    build:   
      context: Servidor-Broker/
      dockerfile: Dockerfile
    ports:          
      - 8080:8080

    environment:    
      - NOMBRE_APP=Prueba
    
    depends_on:   
      - "base-datos"
    networks:
          - red-app

    healthcheck:
      test: fuser 61616/tcp
      interval: 2s
      timeout: 50s
      retries: 15

  base-datos:
    image: mysql:5.7.26
  
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=db
      - MYSQL_DATABASE=Notificacion_sensores
    volumes:   
      - ~/data_mysql:/var/lib/mysql
    networks:
      - red-app
  
  sensor1:
    build:
      context: Cliente/
      dockerfile: Dockerfile
    
    networks:
      - red-app
    command: bash -c "sleep 60 && cd /app && java -jar Cliente.jar 1"

  sensor2:
    build:
      context: Cliente/
      dockerfile: Dockerfile

    networks:
      - red-app
    command: bash -c "sleep 60 && cd /app && java -jar Cliente.jar 2"

networks:  
  red-app:   
